name: Build game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Checksout repository
      - uses: actions/checkout@v4
      # Install Java
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' 
          java-version: '17'
      - name: Grandle permission
        run: chmod -R 777 ./gradlew
      # Build APK
      - name: Build APK
        run: ./gradlew assembleRelease
        
      # Build AAB
      - name: Build AAB
        run: ./gradlew bundleRelease
      # Upload artifacts
      - uses: actions/download-artifact@v8
        with:
          name: builds
          path:
            app/build/outputs/apk/release/
            app/build/outputs/bundle/release/
            
